sudo: false
language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.1
before_script:
  - mkdir tmp
  - git clone https://github.com/elixir-lang/elixir.git tmp/elixir --branch v1.4
script:
  - mix credo tmp/elixir --only readability
